[package]
name = "test_5"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib","rlib"]

[dependencies]

serde = "1.0.126"
yew = "0.18.0"
anyhow = "1.0.41"
wasm-bindgen ="0.2.74"